### PR TITLE
Additional Dependency Warning

### PR DESCRIPTION
**Pull request by jherdman**
An extremely lazy solution to #18.

### CODE REVIEW

**Comment by jherdman** [comment]
I think that sounds great! I tried out your suggested change (which, by the way, is something I didn't know that we could do and is totally awesome) in my app and it worked as expected.

**Comment by jherdman** [comment]
Yay! Finally green!

**Comment by jherdman** [comment]
@rwjblue figured I'd poke you on this. Thoughts on merging?

**Comment by rwjblue** [comment]
Thank you! I must have missed your update after my comment, sorry about that!

**Pull request merged**
